// Produtos mais vendidos para o carrossel
const featuredProducts = [
    { image: 'images/products/alcool-70.jfif', name: 'Álcool 70%' },
    { image: 'images/products/detergente-5-litros.jfif', name: 'Detergente 5 Litros' },
    { image: 'images/products/agua-sanitario-bio-kriss.jfif', name: 'Água Sanitária Bio Kriss' },
    { image: 'images/products/desinfetante-5-litros.jfif', name: 'Desinfetante 5 Litros' },
    { image: 'images/products/papel-toalha.jfif', name: 'Papel Toalha' },
    { image: 'images/products/sabao-em-po-urca.jfif', name: 'Sabão em Pó Urca' },
    { image: 'images/products/veja-gold.jfif', name: 'Veja Gold' },
    { image: 'images/products/luva-pvc.jfif', name: 'Luva PVC' }
];

// Lista completa de produtos com imagens
const products = [
    { image: 'images/products/agua-sanitario-bio-kriss.jfif', name: 'Água Sanitária Bio Kriss' },
    { image: 'images/products/agua-sanitario-clean-up.jfif', name: 'Água Sanitária Clean Up' },
    { image: 'images/products/alcool-70-5-litros-perfumado.jfif', name: 'Álcool 70% 5 Litros Perfumado' },
    { image: 'images/products/alcool-70-5-litros.jfif', name: 'Álcool 70% 5 Litros' },
    { image: 'images/products/alcool-70.jfif', name: 'Álcool 70%' },
    { image: 'images/products/alumil.jfif', name: 'Alumil' },
    { image: 'images/products/balde.jfif', name: 'Balde' },
    { image: 'images/products/bota-com-ca-cano-longo.jfif', name: 'Bota com CA Cano Longo' },
    { image: 'images/products/bota-de-limpeza-com-ca.jfif', name: 'Bota de Limpeza com CA' },
    { image: 'images/products/cera-liquida-polylar.jfif', name: 'Cera Líquida Polylar' },
    { image: 'images/products/cera-liquida-preta.jfif', name: 'Cera Líquida Preta' },
    { image: 'images/products/cloro-5-suprema.jfif', name: 'Cloro 5% Suprema' },
    { image: 'images/products/cloro-ativo.jfif', name: 'Cloro Ativo' },
    { image: 'images/products/coala.jfif', name: 'Coala' },
    { image: 'images/products/copo-descartavel.jfif', name: 'Copo Descartável' },
    { image: 'images/products/desinfetante-5-litros.jfif', name: 'Desinfetante 5 Litros' },
    { image: 'images/products/detergente-5-litros.jfif', name: 'Detergente 5 Litros' },
    { image: 'images/products/detergente-clorado.jfif', name: 'Detergente Clorado' },
    { image: 'images/products/detergente-ype.jfif', name: 'Detergente Ypê' },
    { image: 'images/products/esponja-antirrisco.jfif', name: 'Esponja Antirrisco' },
    { image: 'images/products/esponsa.jfif', name: 'Esponja' },
    { image: 'images/products/flanelas.jfif', name: 'Flanelas' },
    { image: 'images/products/lavanda-suprema.jfif', name: 'Lavanda Suprema' },
    { image: 'images/products/limpa-ceramicas-azulim.jfif', name: 'Limpa Cerâmicas Azulim' },
    { image: 'images/products/limpa-pedra.jfif', name: 'Limpa Pedra' },
    { image: 'images/products/limpa-vidros-suprema.jfif', name: 'Limpa Vidros Suprema' },
    { image: 'images/products/lustra-moveis-bry-jasmim.jfif', name: 'Lustra Móveis BRY Jasmim' },
    { image: 'images/products/lustra-moveis-fuzeto.jfif', name: 'Lustra Móveis Fuzeto' },
    { image: 'images/products/lustra-moveis-uau-perfumes.jfif', name: 'Lustra Móveis UAU Perfumes' },
    { image: 'images/products/luva-pvc.jfif', name: 'Luva PVC' },
    { image: 'images/products/luvas-pvc.jfif', name: 'Luvas PVC' },
    { image: 'images/products/nobre-400-folhas.jfif', name: 'Nobre 400 Folhas' },
    { image: 'images/products/pa-cabo-longo.jfif', name: 'Pá Cabo Longo' },
    { image: 'images/products/pa.jfif', name: 'Pá' },
    { image: 'images/products/pacote-luva-pcv.jfif', name: 'Pacote Luva PCV' },
    { image: 'images/products/paninho-de-micro-fibra.jfif', name: 'Paninho de Microfibra' },
    { image: 'images/products/pano-de-chao.jfif', name: 'Pano de Chão' },
    { image: 'images/products/pano-de-chao002.jfif', name: 'Pano de Chão' },
    { image: 'images/products/pano-multi-uso.jfif', name: 'Pano Multi-uso' },
    { image: 'images/products/papel-higienico.jfif', name: 'Papel Higiênico' },
    { image: 'images/products/papel-toalha.jfif', name: 'Papel Toalha' },
    { image: 'images/products/pasta-de-brilho-aluminio.jfif', name: 'Pasta de Brilho Alumínio' },
    { image: 'images/products/pato-limpeza-profunda.jfif', name: 'Pato Limpeza Profunda' },
    { image: 'images/products/pedra-sanitaria-azulim-acao-bacteriostatica.jfif', name: 'Pedra Sanitária Azulim Ação Bacteriostática' },
    { image: 'images/products/pedra-sanitaria-azulim-floral.jfif', name: 'Pedra Sanitária Azulim Floral' },
    { image: 'images/products/pedra-sanitaria-lipex.jfif', name: 'Pedra Sanitária Lipex' },
    { image: 'images/products/pedra-sanitaria.jfif', name: 'Pedra Sanitária' },
    { image: 'images/products/placa-sinalizacao-piso-molhado.jfif', name: 'Placa Sinalização Piso Molhado' },
    { image: 'images/products/removedor-multi-uso.jfif', name: 'Removedor Multi-uso' },
    { image: 'images/products/rodinho-de-pia.jfif', name: 'Rodinho de Pia' },
    { image: 'images/products/rodo-001.jfif', name: 'Rodo' },
    { image: 'images/products/rodo-002.jfif', name: 'Rodo' },
    { image: 'images/products/rodo-003.jfif', name: 'Rodo' },
    { image: 'images/products/sabao-barra-coco.jfif', name: 'Sabão Barra Coco' },
    { image: 'images/products/sabao-em-po-urca.jfif', name: 'Sabão em Pó Urca' },
    { image: 'images/products/sabao-glicerinado.jfif', name: 'Sabão Glicerinado' },
    { image: 'images/products/saches-de-acucar.jfif', name: 'Sachês de Açúcar' },
    { image: 'images/products/sapolio-multiuso-cremoso.jfif', name: 'Sapólio Multiuso Cremoso' },
    { image: 'images/products/sem-nome001.jfif', name: 'Produto Especial 001' },
    { image: 'images/products/sem-nome002.jfif', name: 'Produto Especial 002' },
    { image: 'images/products/sem-nome003.jfif', name: 'Produto Especial 003' },
    { image: 'images/products/sem-nome004.jfif', name: 'Produto Especial 004' },
    { image: 'images/products/sem-nome005.jfif', name: 'Produto Especial 005' },
    { image: 'images/products/sem-nome006.jfif', name: 'Produto Especial 006' },
    { image: 'images/products/sem-nome007.jfif', name: 'Produto Especial 007' },
    { image: 'images/products/sem-nome008.jfif', name: 'Produto Especial 008' },
    { image: 'images/products/sem-nome009.jfif', name: 'Produto Especial 009' },
    { image: 'images/products/sem-nome010.jfif', name: 'Produto Especial 010' },
    { image: 'images/products/sem-nome011.jfif', name: 'Produto Especial 011' },
    { image: 'images/products/sem-nome012.jfif', name: 'Produto Especial 012' },
    { image: 'images/products/sem-nome013.jfif', name: 'Produto Especial 013' },
    { image: 'images/products/sem-nome014.jfif', name: 'Produto Especial 014' },
    { image: 'images/products/sem-nome015.jfif', name: 'Produto Especial 015' },
    { image: 'images/products/sem-nome016.jfif', name: 'Produto Especial 016' },
    { image: 'images/products/sem-nome017.jfif', name: 'Produto Especial 017' },
    { image: 'images/products/sem-nome018.jfif', name: 'Produto Especial 018' },
    { image: 'images/products/sem-nome019.jfif', name: 'Produto Especial 019' },
    { image: 'images/products/sem-nome020.jfif', name: 'Produto Especial 020' },
    { image: 'images/products/sem-nome021.jfif', name: 'Produto Especial 021' },
    { image: 'images/products/tixam-ype-sabao-em-po.jfif', name: 'Tixam Ypê Sabão em Pó' },
    { image: 'images/products/toalha-de-papel.jfif', name: 'Toalha de Papel' },
    { image: 'images/products/vaselina-liquida.jfif', name: 'Vaselina Líquida' },
    { image: 'images/products/vassoura-001.jfif', name: 'Vassoura' },
    { image: 'images/products/vassoura-002.jfif', name: 'Vassoura' },
    { image: 'images/products/vassoura-003.jfif', name: 'Vassoura' },
    { image: 'images/products/veja-gold.jfif', name: 'Veja Gold' },
    { image: 'images/products/vorel-perform-desinfetante.jfif', name: 'Vorel Perform Desinfetante' },
    { image: 'images/products/x-14.jfif', name: 'X-14' }
];

// Descrições aleatórias para os produtos
const descriptions = [
    'Produto de alta qualidade para limpeza profissional. Ideal para uso industrial e residencial.',
    'Solução eficiente e econômica para suas necessidades de limpeza diária.',
    'Formulado com ingredientes de primeira linha para máxima eficácia e segurança.',
    'Produto testado e aprovado, garantindo resultados superiores em cada uso.',
    'Perfeito para ambientes que exigem limpeza profunda e desinfecção completa.',
    'Economia e praticidade em um único produto. Rendimento superior comprovado.',
    'Desenvolvido especialmente para profissionais que buscam excelência em limpeza.',
    'Qualidade premium com preço justo. A melhor opção para seu negócio.',
    'Produto versátil que atende múltiplas necessidades de limpeza e higienização.',
    'Tecnologia avançada que garante limpeza eficiente e proteção duradoura.'
];

